# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('pick_up_date', models.DateField(default=django.utils.timezone.now)),
                ('year_of_make', models.IntegerField(blank=True, null=True)),
                ('additional_service', models.CharField(max_length=50)),
            ],
        ),
    ]
