# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='car_make',
            field=models.IntegerField(choices=[(0, 'Ford'), (1, 'Tata'), (2, 'Hyundai')], null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='car_model',
            field=models.IntegerField(choices=[(0, 'Eco Sport'), (1, 'Figo'), (2, 'Indica'), (3, 'Indigo'), (4, 'Nano')], null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.IntegerField(choices=[(0, 'RUBBING POLISHING'), (1, 'DRY CLEANING')], null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.CharField(default='Gurgaon', max_length=20),
        ),
    ]
