# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='car_make',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
