# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20160709_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='car_model',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
