# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20160710_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
