# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20160711_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[(0, 'RUBBING POLISHING'), (1, 'DRY CLEANING')], max_length=20, null=True),
        ),
    ]
