# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20160710_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_id',
            field=models.IntegerField(null=True),
        ),
    ]
