# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_auto_20160711_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('RUBBING POLISHING', 'RUBBING POLISHING'), ('DRY CLEANING', 'DRY CLEANING')], max_length=20, null=True),
        ),
    ]
