# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_auto_20160711_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pick_up_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
